### ISSUE TITLE
Custom characters & v1.001 DATA.WIN

### ISSUE THREAD

**Issue by SnowyNix** [SL-RU/UnderTranslator#1]
So, I have two issues:

1: I know it's possible, but I find it very unclear. How do I get my custom glyphs to show up in the app?

2: The app fails to extract the v1.001 data.win file.

Thanks for any help

**Comment by SL-RU** [comment]
1) You need to extract data.win, create folder FONT_new and lay new fonts there.
![screenshot 949](https://cloud.githubusercontent.com/assets/4263405/19203406/b544eb66-8cdf-11e6-98c9-e677984f935d.png)
![screenshot 950](https://cloud.githubusercontent.com/assets/4263405/19203407/b5477142-8cdf-11e6-9d1f-f3129766dafe.png)

After that you need to change fontnames.txt. In my case it will be look so:

```
fnt_papyrus.gmx
fnt_comicsans.gmx
fnt_maintext.gmx
fnt_plain.gmx
```

Lines must contain new font names:

```
Fonts:
1) Papyrus
2) Sans
3) Main
4) Plain
```

2) Hmm, I tested it now. Everything is ok... Did you download binary or built by yourself? Did you put extraction utilities there?
